APP_NAME="SSO (สมอ.)"
APP_ENV=local
APP_KEY=base64:GrJKGN7ns57/N8mJENNNoa9LES03W4hF5e4RmN88/MI=
APP_DEBUG=true
0
# --- แก้ไขให้เป็น Localhost ครับ ---
APP_URL=https://dev.tisi.go.th/tisi_sso
# --------------------------------

APP_TIME_ZONE=Asia/Bangkok

APP_LOG=daily
LOG_CHANNEL=stack

DB_CONNECTION=
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

## DB Elicense
DB_CONNECTION_ElICENSE=
DB_HOST_ElICENSE=
DB_PORT_ElICENSE=
DB_DATABASE_ElICENSE=
DB_USERNAME_ElICENSE=
DB_PASSWORD_ElICENSE=

SESSION_DOMAIN=.tisi.go.th

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=540
SESSION_COOKIE=sso_session
SESSION_SECURE_COOKIE=false
SESSION_SAME_SITE=lax
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

#  URL 16/10/2568 Kantapon
TISI_LOGIN_URL=https://www3.tisi.go.th/moiapi/LoginIndust.asp



MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.workd.go.th
MAIL_PORT=465
MAIL_USERNAME=noreply-tisi5@tisi.mail.go.th
MAIL_PASSWORD="aseZrkFUDruk78uZo4rbg6f39xeMYgrnQ4grcAxzQRxBCBmsur2L8VoX6AKYKKNU"
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=tisi_regis@tisi.mail.go.th
MAIL_FROM_NAME="NoReply Mail From TISI-SSO (NoReply)"

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

FILESYSTEM_DRIVER=ftp
FILESYSTEM_ROOT_URL=https://nas16.tisi.go.th
FILESYSTEM_FTP_HOST=203.154.78.16
FILESYSTEM_FTP_PORT=21
FILESYSTEM_FTP_USERNAME=surve_ram
FILESYSTEM_FTP_PASSWORD=tisi@123456
FILESYSTEM_FTP_ROOT=surve_ram/itisi-attach